apiVersion: v1
kind: Pod
metadata:
  name: envPod
  namespace: expense
  labels:
    project: expense
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: devops