apiVersion: v1
kind: Pod
metadata:
  name: podconfig
  namespace: expense
  labels:
    project: expense
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      configMapKeyRef:
        name: nginx.config
        key: course
    - name: mode
      configMapKeyRef:
        name: nginx.config
        key: mode