apiVersion: v1
kind: Pod
metadata:
  name: podconfig
  namespace: expense
  labels:
    project: expense
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: nginx.conf
    # env:
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: nginx.config
    #       key: course
    # - name: mode
    #   valueFrom:
    #     configMapKeyRef:
    #       name: nginx.config
    #       key: mode