apiVersion: v1
kind: Pod
metadata:
  name: podsecret
  namespace: expense
  labels:
    project: expense
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod.secret