apiVersion: v1
kind: Service
metadata:
  namespace: expense
  name: nodeport.service
spec:
  type: NodePort
  selector:
    project: expense
    environment: dev
  ports:
    - port: 80
      containerPort: 80